spring:
  data:
    jpa:
      show-sql: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: NON_ABSENT
    mapper:
      sort-properties-alphabetically: true
    serialization:
      write-dates-as-timestamps: false
  main:
    banner-mode: log

management:
  address: 127.0.0.1
  context-path: /manage
  port: 8081
